spring:
  datasource:
    url: jdbc:mysql://localhost/mybatis?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&mysqlEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: com.example.springfcm
  mapper-locations: /mapper/**/*.xml

fcm:
  account:
    path: "/Users/choejeong-gyun/Documents/Spring-FCM/src/main/resources/firebase.json"